@startuml

title __DATABASE's Class Diagram__\n

  namespace  {
    namespace om.example.cursjavafx {
      namespace database {
        class com.example.cursjavafx.database.PostgreDB {
            {static} + idAnimal : int
            {static} + idUser : int
            {static} + kindAnimal : String
            {static} + nameAnimal : String
            {static} + prescribing : String
            {static} + singleBD : PostgreDB
            {static} ~ DB_URL : String
            {static} ~ PASS : String
            {static} ~ USER : String
            - connection : Connection
            {static} + calcDateEnd()
            + createAnimal()
            + createCalendarMap()
            + createEvent()
            + createEventreglament()
            + createUser()
            + deleteAnimal()
            + deleteEvent()
            + getAnimals()
            + getCalendarActivitiesMonth()
            + getEvents()
            + getKinds()
            + getPills()
            + getPrescribing()
            + loginUser()
            + setConnection()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.cursjavafx {
      namespace database {
        interface com.example.cursjavafx.database.dbDao {
            {abstract} + createAnimal()
            {abstract} + createCalendarMap()
            {abstract} + createEvent()
            {abstract} + createEventreglament()
            {abstract} + createUser()
            {abstract} + deleteAnimal()
            {abstract} + deleteEvent()
            {abstract} + getAnimals()
            {abstract} + getCalendarActivitiesMonth()
            {abstract} + getEvents()
            {abstract} + getKinds()
            {abstract} + getPills()
            {abstract} + getPrescribing()
            {abstract} + loginUser()
            {abstract} + setConnection()
            - calcDateEnd()
        }
      }
    }
  }
  

  com.example.cursjavafx.database.PostgreDB .up.|> com.example.cursjavafx.database.dbDao


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
