@startuml

title __CLASSES's Class Diagram__\n

  namespace  {
    namespace om.example.cursjavafx {
      namespace classes {
        class com.example.cursjavafx.classes.Animal {
            ~ date_birth : Date
            ~ id : int
            ~ kind : String
            ~ name : String
            + Animal()
            + getDate_birth()
            + getId()
            + getKind()
            + getName()
            + setDate_birth()
            + setId()
            + setKind()
            + setName()
            + toString()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.cursjavafx {
      namespace classes {
        class com.example.cursjavafx.classes.CalendarActivity {
            - clientName : String
            - date : ZonedDateTime
            - eventInfo : Boolean
            - event_name : String
            + CalendarActivity()
            + getClientName()
            + getDate()
            + getEventInfo()
            + getEvent_name()
            + setClientName()
            + setDate()
            + setEventInfo()
            + setEvent_name()
            + toString()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.cursjavafx {
      namespace classes {
        class com.example.cursjavafx.classes.EventsAnimals {
            ~ date_end : Date
            ~ date_start : Date
            ~ id : int
            ~ name : String
            + EventsAnimals()
            + getDate_end()
            + getDate_start()
            + getId()
            + getName()
            + setDate_end()
            + setDate_start()
            + setId()
            + setName()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.cursjavafx {
      namespace classes {
        class com.example.cursjavafx.classes.Pills {
            ~ days : int
            ~ id : int
            ~ name : String
            + Pills()
            + getDays()
            + getId()
            + getName()
            + setDays()
            + setId()
            + setName()
            + toString()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
